# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - internal_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup  # Mount backup file
  matching_service:
    image: matching-service:1.0
    ports:
      - "3500:8000"
    networks:
      - internal_network
  driver_service:
    image: driver-service:1.0
    ports:
      - "4500:8000"
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge
volumes:
  postgres_data:  # Define the named volume