"""Recreate migration

Revision ID: 7049b3160e39
Revises: bc82244e524e
Create Date: 2025-02-10 23:30:32.789885

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7049b3160e39'
down_revision: Union[str, None] = 'bc82244e524e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rideoffer', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rideoffer', 'price')
    # ### end Alembic commands ###
