"""Recreate migration

Revision ID: a9b2d2f2b72c
Revises: 7049b3160e39
Create Date: 2025-02-10 23:56:37.084462

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b2d2f2b72c'
down_revision: Union[str, None] = '7049b3160e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'fcm_token')
    # ### end Alembic commands ###
