"""Add timestamp in RideOffer

Revision ID: cb80585cd022
Revises: dfa1d20c9136
Create Date: 2025-02-14 16:14:12.760692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb80585cd022'
down_revision: Union[str, None] = 'dfa1d20c9136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rideoffer', sa.Column('timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rideoffer', 'timestamp')
    # ### end Alembic commands ###
