FROM python:3.13-slim
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN pip install -r requirements.txt
EXPOSE 4500
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]